apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadeffj8396-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadeffj8396-tenant-component
    app.kubernetes.io/part-of: loadeffj8396-tenant-app
  name: loadeffj8396-tenant-component
  namespace: loadeffj8396-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadeffj8396-tenant-component
    weight: null
status: {}
